name: js_ast
author: Dart Team <misc@dartlang.org>
description: Library creating and printing JavaScript ASTs.
homepage: http://www.dartlang.org
dev_dependencies:
  test: ^1.3.4
environment:
  sdk: ">=0.8.10+6 <2.0.0"
