name: diagnostic
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Diagnostics for Dart
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/diagnostic
environment:
  sdk: '>=2.0.0-dev.48.0 <3.0.0'
